name: Deploy to GitHub Pages
on: [push]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install --frozen-lockfile
      - name: Deploy
        uses: borales/actions-yarn@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.MASTER_TOKEN }}
        with:
          cmd: deploy
