name: Deploy to GitHub Pages

on:
  push:
    paths:
      - "src/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install dependencies
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install --frozen-lockfile

    - name: Run unit tests
      uses: borales/actions-yarn@v2.3.0
      with:
        cmd: test

    - name: Prepare and deploy
      uses: borales/actions-yarn@v2.3.0
      env:
        GITHUB_TOKEN: ${{ secrets.MASTER_TOKEN }}
      with:
        cmd: deploy --no-silent
